### ISSUE TITLE
ImportError: No module named PIL

### ISSUE THREAD

**Issue by yikoujinxin** [livezingy/tesstrain-win#2]
Traceback (most recent call last):
  File "generate_line_box.py", line 6, in <module>
    from PIL import Image
ImportError: No module named PIL
make: *** [Makefile:184: data/foo-ground-truth/vischer_auch02_1879_0328_011.box] Error 1

**Comment by livezingy** [comment]
Set up python3.6+ and intsall the PIL model with `pip install Pillow ` please
